/*
  Bakes the build version into the Worker as a JS module import.
  Mirrors the pattern from drep-learncardano: the SHA is inlined
  into the HTML at the edge via HTMLRewriter, so the browser never
  needs to fetch a /version.json file to know the current build.
*/
import { writeFileSync, mkdirSync } from "node:fs";
import { execSync } from "node:child_process";

let sha =
  process.env.WORKERS_CI_COMMIT_SHA ||
  process.env.CF_PAGES_COMMIT_SHA ||
  process.env.GITHUB_SHA ||
  "";

if (!sha) {
  try {
    sha = execSync("git rev-parse HEAD", {
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
  } catch {
    /* no git available */
  }
}

const VERSION = {
  sha: sha.slice(0, 7) || "dev",
  fullSha: sha || null,
  builtAt: new Date().toISOString(),
};

mkdirSync("src", { recursive: true });
writeFileSync(
  "src/version-data.js",
  `// Generated by build.js at deploy — do not edit by hand.\nexport const VERSION = ${JSON.stringify(VERSION, null, 2)};\n`,
);
console.log("wrote src/version-data.js:", VERSION);
