/*
  Stamps the build version into src/version-data.js (imported by the Worker)
  AND copies hand-written assets from src/static/ into public/.

  public/ is fully regenerated by the build pipeline — never edit files
  in there by hand. Source of truth:
    - src/static/      hand-written HTML, CSS, images
    - src/content/     migrated WordPress posts + comments
    - src/templates/   page templates for build-posts.js
*/
import { writeFileSync, readFileSync, mkdirSync, cpSync, rmSync, existsSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { execSync } from "node:child_process";
import * as esbuild from "esbuild";

/* ---------------- version stamp ---------------- */

let sha =
  process.env.WORKERS_CI_COMMIT_SHA ||
  process.env.CF_PAGES_COMMIT_SHA ||
  process.env.GITHUB_SHA ||
  "";

if (!sha) {
  try {
    sha = execSync("git rev-parse HEAD", { stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch { /* no git */ }
}

const VERSION = {
  sha: sha.slice(0, 7) || "dev",
  fullSha: sha || null,
  builtAt: new Date().toISOString(),
};

mkdirSync("src", { recursive: true });
writeFileSync(
  "src/version-data.js",
  `// Generated by build.js — do not edit by hand.\nexport const VERSION = ${JSON.stringify(VERSION, null, 2)};\n`,
);
console.log("✓ src/version-data.js stamped:", VERSION.sha, VERSION.builtAt);

/* ---------------- clean + copy src/static -> public ---------------- */

const PUBLIC = "public";
const STATIC = "src/static";

// Wipe public/ but keep .gitkeep so the dir stays tracked.
if (existsSync(PUBLIC)) {
  for (const entry of readdirSync(PUBLIC)) {
    if (entry === ".gitkeep") continue;
    rmSync(join(PUBLIC, entry), { recursive: true, force: true });
  }
}
mkdirSync(PUBLIC, { recursive: true });

if (existsSync(STATIC)) {
  cpSync(STATIC, PUBLIC, { recursive: true });
  console.log(`✓ copied ${STATIC}/ -> ${PUBLIC}/ (${countFiles(STATIC)} files)`);
}

/* ---------------- minify CSS + JS in place ---------------- */

await minifyAsset(join(PUBLIC, "styles/main.css"), "css");
for (const f of readdirSync(join(PUBLIC, "scripts")).filter((n) => n.endsWith(".js"))) {
  await minifyAsset(join(PUBLIC, "scripts", f), "js");
}

async function minifyAsset(path, loader) {
  if (!existsSync(path)) return;
  const src = readFileSync(path, "utf8");
  const before = src.length;
  const result = await esbuild.transform(src, {
    loader,
    minify: true,
    target: loader === "js" ? "es2020" : undefined,
    legalComments: "none",
  });
  writeFileSync(path, result.code);
  const after = result.code.length;
  const pct = ((1 - after / before) * 100).toFixed(1);
  console.log(`  ✓ minified ${path.replace(PUBLIC + "/", "")}: ${before.toLocaleString()}B → ${after.toLocaleString()}B (-${pct}%)`);
}

function countFiles(dir) {
  let n = 0;
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    n += statSync(p).isDirectory() ? countFiles(p) : 1;
  }
  return n;
}
