/*
  Bundles @meshsdk/core into a single self-hosted ESM file
  served from /vendor/mesh.mjs (with any WASM emitted alongside).
  Run via `npm run build:mesh` (auto-runs as part of `npm run build`).
*/
import * as esbuild from "esbuild";
import { polyfillNode } from "esbuild-plugin-polyfill-node";
import { mkdirSync, existsSync, rmSync } from "node:fs";

const OUT_DIR = "public/vendor";

if (existsSync(OUT_DIR)) rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const result = await esbuild.build({
  entryPoints: ["vendor-mesh-entry.js"],
  bundle: true,
  format: "esm",
  target: "es2022",
  platform: "browser",
  outfile: `${OUT_DIR}/mesh.mjs`,
  loader: { ".wasm": "file" },
  assetNames: "[name]-[hash]",
  publicPath: "/vendor/",
  minify: true,
  legalComments: "none",
  sourcemap: false,
  define: {
    "process.env.NODE_ENV": '"production"',
    global: "globalThis",
  },
  banner: { js: "// Mesh SDK browser bundle — generated by build-mesh.js" },
  plugins: [
    polyfillNode({
      polyfills: {
        crypto: true,
        stream: true,
        events: true,
        buffer: true,
        util: true,
        process: true,
      },
      globals: { buffer: true, process: true },
    }),
  ],
  metafile: true,
  logLevel: "info",
});

const outputs = Object.keys(result.metafile.outputs);
console.log("\n✓ Mesh bundle written:", outputs.join(", "));
